### ISSUE TITLE
Github page not displaying markdown correctly

### ISSUE THREAD

**Issue by mfernandes61** [tavareshugo/2018-04-16-cambridge#3]
Hugo - the Day 1 & Day 2 areas Markdown code does not get rendered.
If edit on web then preview changes show rendered fine.
Cloned repo onto my mac and looked at index.md with MacDown and it displayed fine.
Think it must be jeckyll-realted i.e. when it generates the static page?

**Comment by tavareshugo** [comment]
Thanks for pointing this out. Seems to be fixed now. Basically replaced it with a chunk of html instead. 
(it should be possible to use markdown syntax there, but I couldn't figure it out...)
